# Generated by Django 5.0.2 on 2024-04-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='descreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
